"""Signal graduation. Verdicts are applied by rule, from evidence, against thresholds fixed
in PLAN.md before any result was seen — so the bar cannot be moved to fit the outcome.

`reports/signal_scorecards.md` and the README summary table are generated from here. Neither
is hand-edited; both are regenerated by `flightrisk scorecards`.
"""

from __future__ import annotations

import pandas as pd

from . import signals  # noqa: F401
from .config import REPORTS
from .registry import REGISTRY, Status, save_evidence

# ---- preregistered thresholds -------------------------------------------------
INCREMENTAL_MIN = 0.05  # removing the signal must cost >= this much lift@5%
STANDALONE_INFORMATIVE = 1.15  # standalone lift@5% above this means it carries information
STANDALONE_NULL = 1.05  # at or below this it is indistinguishable from random ranking
STABILITY_MIN = 0.70  # fraction of walk-forward folds with standalone lift > 1
SEVERE_CONSISTENT = 1.15  # also ranks the -10% tier => not threshold-specific


def _verdict(r: pd.Series) -> tuple[Status, str]:
    inc = r.get("incremental_lift_5pct")
    solo = r.get("standalone_lift_5pct")
    stab = r.get("standalone_lift_frac_folds_above_1")
    inc = float(inc) if pd.notna(inc) else 0.0
    solo = float(solo) if pd.notna(solo) else 0.0
    stab = float(stab) if pd.notna(stab) else 0.0

    if r.get("macro"):
        return (
            Status.KILLED,
            "Constant within a quarter, so it cannot rank banks inside the quarter an alert "
            "list is worked in; its apparent value is entirely pooled-metric inflation.",
        )
    if inc >= INCREMENTAL_MIN and stab >= STABILITY_MIN:
        return (
            Status.GRADUATED,
            f"Removing it costs {inc:.2f} lift@5%, and it beats random ranking in "
            f"{stab:.0%} of walk-forward folds.",
        )
    if inc >= INCREMENTAL_MIN:
        return (
            Status.PARKED,
            f"Adds {inc:.2f} incremental lift@5% but is unstable across folds "
            f"({stab:.0%} above random) — plausible regime artifact, not yet trustworthy.",
        )
    if solo > STANDALONE_INFORMATIVE:
        return (
            Status.PARKED,
            f"Carries real standalone information (lift {solo:.2f}) but is redundant once the "
            f"graduated set is present (incremental {inc:+.2f}).",
        )
    if solo <= STANDALONE_NULL:
        return (
            Status.KILLED,
            f"No standalone ranking power (lift {solo:.2f}) and no incremental "
            f"contribution ({inc:+.2f}).",
        )
    return (
        Status.KILLED,
        f"Weak standalone (lift {solo:.2f}) and no incremental contribution ({inc:+.2f}).",
    )


def apply_verdicts(ablations: pd.DataFrame) -> pd.DataFrame:
    rows = []
    for _, r in ablations.iterrows():
        sig = REGISTRY.get(r["signal"])
        if sig is None:
            continue
        status, reason = _verdict(r)
        sig.status = status
        sig.evidence = {
            k: (None if pd.isna(r.get(k)) else float(r.get(k)))
            for k in [
                "standalone_lift_5pct",
                "standalone_precision_5pct",
                "standalone_auc_within_q",
                "standalone_lift_frac_folds_above_1",
                "incremental_lift_5pct",
                "incremental_precision_5pct",
                "standalone_lift_5pct_severe",
            ]
            if k in r.index
        }
        sig.evidence["verdict_reason"] = reason
        rows.append(
            {
                "signal": sig.name,
                "family": sig.family,
                "rationale": sig.rationale,
                "status": status.value,
                "dumb": bool(r.get("dumb", False)),
                "standalone_lift_5pct": r.get("standalone_lift_5pct"),
                "incremental_lift_5pct": r.get("incremental_lift_5pct"),
                "stability_frac_folds": r.get("standalone_lift_frac_folds_above_1"),
                "severe_tier_lift_5pct": r.get("standalone_lift_5pct_severe"),
                "reason": reason,
            }
        )
    out = pd.DataFrame(rows)
    save_evidence()
    return out


def _fmt(v, nd=3) -> str:
    return "—" if v is None or pd.isna(v) else f"{float(v):.{nd}f}"


def write_markdown(cards: pd.DataFrame, headline: dict | None = None) -> str:
    order = {"GRADUATED": 0, "PARKED": 1, "KILLED": 2, "CANDIDATE": 3}
    c = cards.sort_values(
        ["status", "incremental_lift_5pct"],
        key=lambda s: s.map(order) if s.name == "status" else -s.fillna(-99),
    )
    lines = [
        "# Signal graduation scorecards",
        "",
        "Generated by `flightrisk scorecards` from the registry. Do not edit by hand.",
        "",
        "**Metric.** `lift@5%` is within-quarter precision@top-5% divided by that quarter's "
        "base rate, macro-averaged over 28 walk-forward test quarters (2019Q1–2025Q4). "
        "1.00 means no better than ranking at random inside the quarter.",
        "",
        "**Thresholds, fixed before results were seen:** GRADUATE needs incremental "
        f"lift ≥ {INCREMENTAL_MIN} *and* stability ≥ {STABILITY_MIN:.0%} of folds. PARK means "
        "real information but redundant, or useful but unstable. KILL means neither.",
        "",
        "| Signal | Status | Standalone lift@5% | Incremental lift@5% | "
        "Stability (folds > random) | Severe -10% lift | Rationale |",
        "|---|---|---|---|---|---|---|",
    ]
    for _, r in c.iterrows():
        badge = {"GRADUATED": "**GRADUATED**", "PARKED": "PARKED", "KILLED": "~~KILLED~~"}.get(
            r["status"], r["status"]
        )
        name = f"`{r['signal']}`" + (" ⚠︎null" if r["dumb"] else "")
        lines.append(
            f"| {name} | {badge} | {_fmt(r['standalone_lift_5pct'])} | "
            f"{_fmt(r['incremental_lift_5pct'])} | {_fmt(r['stability_frac_folds'], 2)} | "
            f"{_fmt(r['severe_tier_lift_5pct'])} | {r['rationale']} |"
        )

    lines += ["", "## Verdict reasoning", ""]
    for status in ["GRADUATED", "PARKED", "KILLED"]:
        sub = c[c["status"] == status]
        if sub.empty:
            continue
        lines.append(f"### {status} ({len(sub)})")
        lines.append("")
        for _, r in sub.iterrows():
            lines.append(f"- **`{r['signal']}`** — {r['reason']}")
        lines.append("")

    dumb = c[c["dumb"]]
    if len(dumb):
        killed = (dumb["status"] == "KILLED").all()
        lines += [
            "## Tripwire check",
            "",
            f"{len(dumb)} deliberately-null signals were registered as a live check on this "
            "framework. "
            + (
                "**All were KILLED**, as required — the graduation rules reject content-free "
                "features."
                if killed
                else "**A null signal survived — the framework is broken and these results "
                "are void.**"
            ),
            "",
        ]
    if headline:
        lines += [
            "## Full-model reference",
            "",
            "HistGB on the structured set: precision@1% "
            f"{headline.get('precision_at_1pct', 0):.3f} "
            f"(lift {headline.get('lift_at_1pct', 0):.2f}), precision@5% "
            f"{headline.get('precision_at_5pct', 0):.3f} "
            f"(lift {headline.get('lift_at_5pct', 0):.2f}), "
            f"within-quarter ROC-AUC {headline.get('roc_auc_within_quarter', 0):.3f}, "
            f"base rate {headline.get('base_rate', 0):.4f}.",
            "",
        ]
    text = "\n".join(lines)
    (REPORTS / "signal_scorecards.md").write_text(text)
    cards.to_csv(REPORTS / "signal_scorecards.csv", index=False)
    return text


README_BEGIN = "<!-- BEGIN:signal-table (generated by `flightrisk scorecards`) -->"
README_END = "<!-- END:signal-table -->"


def write_readme_table(cards: pd.DataFrame) -> bool:
    """Replace the README's signal table with one generated from the registry.

    The table lives between HTML comment markers so the surrounding prose is preserved. If the
    markers are missing the function does nothing rather than mangling the file.
    """
    readme = REPORTS.parent / "README.md"
    if not readme.exists():
        return False
    text = readme.read_text()
    if README_BEGIN not in text or README_END not in text:
        return False

    order = {"GRADUATED": 0, "PARKED": 1, "KILLED": 2, "CANDIDATE": 3}
    c = cards.copy()
    c["_o"] = c["status"].map(order)
    c = c.sort_values(["_o", "incremental_lift_5pct"], ascending=[True, False])

    rows = [
        README_BEGIN,
        "",
        "| Signal | Verdict | Standalone lift@5% | Incremental lift@5% | "
        "Stable folds | -10% tier lift |",
        "|---|---|---|---|---|---|",
    ]
    for _, r in c.iterrows():
        badge = {"GRADUATED": "**GRADUATED**", "PARKED": "PARKED", "KILLED": "~~KILLED~~"}.get(
            r["status"], r["status"]
        )
        tag = " ⚠︎null" if r["dumb"] else ""
        rows.append(
            f"| `{r['signal']}`{tag} | {badge} | {_fmt(r['standalone_lift_5pct'])} | "
            f"{_fmt(r['incremental_lift_5pct'])} | {_fmt(r['stability_frac_folds'], 2)} | "
            f"{_fmt(r['severe_tier_lift_5pct'])} |"
        )
    counts = c["status"].value_counts().to_dict()
    rows += [
        "",
        f"{counts.get('GRADUATED', 0)} graduated, {counts.get('PARKED', 0)} parked, "
        f"{counts.get('KILLED', 0)} killed. Full reasoning: "
        "[`reports/signal_scorecards.md`](reports/signal_scorecards.md).",
        "",
        README_END,
    ]
    start = text.index(README_BEGIN)
    end = text.index(README_END) + len(README_END)
    readme.write_text(text[:start] + "\n".join(rows) + text[end:])
    return True
